### ISSUE TITLE
php81

### ISSUE THREAD

**Issue by didier-lechenne** [esadpyrenees/PageTypeToPrint#5]
hello
très impressionnant !
J'ai cette erreur en version php81.
Fonctionne très bien en php80

![Capture d’écran 2023-09-21 à 15 24 14](https://github.com/esadpyrenees/PageTypeToPrint/assets/12462928/4a89c577-57db-4734-82fa-ea1252c24815)

**Comment by jbidoret** [comment]
Bien reçu, merci ! J’essaie d’envoyer le correctif bientôt.

**Comment by jbidoret** [comment]
C’est corrigé (patch #[\ReturnTypeWillChange] en attendant la mise à jour de la librairie MarkdownIt)
